### ISSUE TITLE
Include More Data?

### ISSUE THREAD

**Issue by pgensler** [jasdumas/ttbbeer#1]
Is it possible to get the full datasets listed on this website, from 1984-2016? I know the format has changed with the files over time and some of the pdf's are image based, but it would be really cool for some time series analysis. I'd love to help contribute with trying to parse these pdf's if you would like, as I think the underlying data would be interesting to look into.

**Comment by jasdumas** [comment]
Hey - Thanks for your message! I don't have time right now but If you would like to parse the PDF's and add more data for the `beermaterials` dataset, feel free to submit a PR :smile: I appreciate the contribution!
